spring.application.name=bookstore
spring.main.allow-bean-definition-overriding=true

# 禁用Spring Boot的数据库数据源自动配置
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# JWT验证相关配置
SECRET_KEY=835ffd9adf627ae7f9f597f7360b69e7473e97ed8ada4f310a45a40f2ba8a562
EXPIRATION_TIME=3600000


# 数据库连接配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore
spring.datasource.username=mybatis_for_bookstore
spring.datasource.password=bookstore1116

# MyBatis mapper 位置
mybatis.mapper-locations=classpath:mapper/*.xml