spring.application.name=bookstore
spring.main.allow-bean-definition-overriding=true

# 禁用Spring Boot的数据源自动配置
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration